/**
 * Shared type definitions and mock simulation data.
 * In production, SimulationRecord instances are created by the Gemini service
 * and persisted to MongoDB Atlas. This file is the single source of truth
 * for types used across the app.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type StakeholderImpact = 'positive' | 'negative' | 'mixed';

/**
 * Maps to an ElevenLabs voice ID for audio generation.
 * Each archetype has a distinct voice persona.
 */
export type VoiceArchetype = 'student' | 'worker' | 'authority' | 'parent' | 'default';

export interface Stakeholder {
  id: string;
  name: string;
  role: string;
  impact: StakeholderImpact;
  isOverlooked: boolean;
  description: string;
  voiceQuote: string;
  voiceArchetype?: VoiceArchetype;
}

export interface ConflictPair {
  groupA: string;
  groupB: string;
  reason: string;
}

export interface SimulationRecord {
  id: string;
  decisionTitle: string;
  decisionText?: string;
  description: string;
  timestamp: string;
  stakeholders: Stakeholder[];
  /** Conflict pairs discovered by Gemini between stakeholder groups */
  conflicts?: ConflictPair[];
  /** Names of stakeholder groups that were overlooked (blind spots) */
  blindSpots?: string[];
  /** Two-sentence overall analysis generated by Gemini */
  summary?: string;
  /** MongoDB document ID, set after persistence */
  mongoId?: string;
}

// ---------------------------------------------------------------------------
// Mock Data — Attendance Policy
// ---------------------------------------------------------------------------

const ATTENDANCE_SIMULATION: SimulationRecord = {
  id: 'sim-1',
  decisionTitle: 'Mandatory 85% attendance policy for all courses',
  decisionText: 'Mandatory 85% attendance policy for all courses',
  description:
    'Requires all students to maintain at least 85% physical attendance to be eligible for final examinations, with no exceptions for internships.',
  timestamp: '2026-06-13T10:30:00Z',
  blindSpots: ['Disabled Students', 'Long-Distance Commuters', 'Working Students'],
  summary:
    'This policy improves classroom engagement but creates measurable hardship for disabled students, long-distance commuters, and working students. Three key groups were not considered during formulation.',
  conflicts: [
    {
      groupA: 'Course Professors',
      groupB: 'Working Students',
      reason:
        'Strict attendance enforcement directly conflicts with part-time employment schedules, forcing students to choose between their income and academic standing.',
    },
    {
      groupA: 'Academic Toppers',
      groupB: 'Long-Distance Commuters',
      reason:
        'Toppers who live on campus have structural advantages that unfairly skew the perceived fairness of the policy against commuters.',
    },
  ],
  stakeholders: [
    {
      id: 'sh-1-1',
      name: 'Disabled Students',
      role: 'Students with physical or chronic health challenges',
      impact: 'negative',
      isOverlooked: true,
      voiceArchetype: 'student',
      description:
        'Getting to campus daily is physically exhausting. Rigid rules make it impossible to handle health flare-ups without risking academic failure.',
      voiceQuote:
        'Getting to campus daily is physically demanding. Some days my condition flares up, and having flexible attendance options is the difference between graduating and dropping out.',
    },
    {
      id: 'sh-1-2',
      name: 'Long-Distance Commuters',
      role: 'Students traveling >1.5 hours one-way',
      impact: 'negative',
      isOverlooked: true,
      voiceArchetype: 'student',
      description:
        'Spend 3–4 hours daily in transit. Any delays or transport disruptions make meeting the strict 85% mark extremely stressful.',
      voiceQuote:
        'I travel over two hours daily. Severe transit delays are common. This strict policy would penalize me for factors entirely out of my control.',
    },
    {
      id: 'sh-1-3',
      name: 'Working Students',
      role: 'Students balancing part-time jobs',
      impact: 'negative',
      isOverlooked: true,
      voiceArchetype: 'worker',
      description:
        'Need to work shifts to fund tuition and living expenses. Class timing conflicts directly threaten their financial stability.',
      voiceQuote:
        'I work shifts to pay for my tuition. A rigid attendance rule forces me to choose between my job—which keeps me in school—and the classes themselves.',
    },
    {
      id: 'sh-1-4',
      name: 'Hostel/On-Campus Students',
      role: 'Students living in university dorms',
      impact: 'mixed',
      isOverlooked: false,
      voiceArchetype: 'student',
      description:
        'Find it easy to attend class but face reduced peer engagement since off-campus group members struggle to make it consistently.',
      voiceQuote:
        'Living on campus makes attendance easy for me. However, my project partners who commute are missing classes, which disrupts our teamwork.',
    },
    {
      id: 'sh-1-5',
      name: 'Course Professors',
      role: 'Teaching staff and instructors',
      impact: 'positive',
      isOverlooked: false,
      voiceArchetype: 'authority',
      description:
        'Benefit from fuller classrooms and consistent student engagement, though they face increased administrative overhead validating sick leaves.',
      voiceQuote:
        'Having full classrooms makes lectures much more engaging. However, I now spend hours checking doctor notes, which is not what I signed up for.',
    },
    {
      id: 'sh-1-6',
      name: 'Academic Toppers',
      role: 'High-performing students',
      impact: 'positive',
      isOverlooked: false,
      voiceArchetype: 'student',
      description:
        'Value classroom interaction and structured lecture settings, which help maintain academic consistency and networking opportunities.',
      voiceQuote:
        'I enjoy attending classes and participating in discussions. It helps me stay disciplined and get immediate feedback from instructors.',
    },
  ],
};

// ---------------------------------------------------------------------------
// Mock Data — Cashless Campus
// ---------------------------------------------------------------------------

const CASHLESS_SIMULATION: SimulationRecord = {
  id: 'sim-2',
  decisionTitle: 'Transitioning to a 100% cashless campus',
  decisionText: 'Transitioning to a 100% cashless campus',
  description:
    'Bans cash payments across all campus canteens, stationery shops, photocopying booths, and administrative services, requiring digital UPI/card payments only.',
  timestamp: '2026-06-12T14:15:00Z',
  blindSpots: ['Contractual Staff & Canteen Workers', 'International Students'],
  summary:
    'A cashless mandate improves administrative efficiency but creates significant exclusion for staff without bank accounts and international students navigating UPI barriers.',
  conflicts: [
    {
      groupA: 'Campus Administration',
      groupB: 'Contractual Staff & Canteen Workers',
      reason:
        'Digital-only payments assume bank account access and smartphone literacy — resources that contractual workers frequently lack.',
    },
  ],
  stakeholders: [
    {
      id: 'sh-2-1',
      name: 'Contractual Staff & Canteen Workers',
      role: 'Non-payroll support staff',
      impact: 'negative',
      isOverlooked: true,
      voiceArchetype: 'worker',
      description:
        'Often paid in cash or rely on immediate cash tips. Many lack digital bank accounts or reliable smartphones to verify payments.',
      voiceQuote:
        'Many of us do not have smartphones or bank accounts linked to digital systems. Cash is how we buy daily groceries for our families.',
    },
    {
      id: 'sh-2-2',
      name: 'International Students',
      role: 'Foreign nationals studying on campus',
      impact: 'negative',
      isOverlooked: true,
      voiceArchetype: 'student',
      description:
        'Struggle to set up local UPI payment accounts due to banking regulations. High foreign transaction fees on international cards make daily purchases expensive.',
      voiceQuote:
        'Setting up UPI as an international student takes weeks of paperwork. Without cash, I could not even buy lunch in my first month.',
    },
    {
      id: 'sh-2-3',
      name: 'Campus Administration',
      role: 'Finance and accounting office',
      impact: 'positive',
      isOverlooked: false,
      voiceArchetype: 'authority',
      description:
        'Eliminates cash handling risk, simplifies bookkeeping, and prevents financial leakage in canteens.',
      voiceQuote:
        'Auditing accounts is ten times easier now. We no longer have to collect physical cash bags or worry about discrepancies.',
    },
    {
      id: 'sh-2-4',
      name: 'Tech-Savvy Students',
      role: 'General digitally-enabled student population',
      impact: 'positive',
      isOverlooked: false,
      voiceArchetype: 'student',
      description:
        'Appreciate fast checkouts and not having to carry physical wallets or exact change.',
      voiceQuote:
        'It is super convenient. I just scan the QR code and go. No more carrying coins or waiting for change.',
    },
  ],
};

// ---------------------------------------------------------------------------
// Mock Data — Return to Office
// ---------------------------------------------------------------------------

const RTO_SIMULATION: SimulationRecord = {
  id: 'sim-3',
  decisionTitle: 'Mandatory return-to-office 5 days a week',
  decisionText: 'Mandatory return-to-office 5 days a week',
  description:
    'Eliminates hybrid work policies, requiring all engineering and support staff to work from physical office locations starting next month.',
  timestamp: '2026-06-10T09:00:00Z',
  blindSpots: ['Working Parents & Caregivers', 'Neurodivergent Employees'],
  summary:
    'A full return-to-office mandate benefits in-person collaboration but creates serious hardship for caregivers and neurodivergent employees whose productivity depends on home-based environments.',
  conflicts: [
    {
      groupA: 'Executive Leadership',
      groupB: 'Working Parents & Caregivers',
      reason:
        'Leadership expects presence-driven productivity gains, but working parents face childcare commitments that cannot be restructured with one month of notice.',
    },
    {
      groupA: 'Executive Leadership',
      groupB: 'Neurodivergent Employees',
      reason:
        'Remote work served as an informal accessibility accommodation. Removing it without individual assessment may violate accessibility commitments.',
    },
  ],
  stakeholders: [
    {
      id: 'sh-3-1',
      name: 'Working Parents & Caregivers',
      role: 'Employees with family responsibilities',
      impact: 'negative',
      isOverlooked: true,
      voiceArchetype: 'parent',
      description:
        'Lose crucial flexibility needed for school drop-offs and elder care, forcing high child-care expenses or career setbacks.',
      voiceQuote:
        'Hybrid work let me manage preschool pickup without missing meetings. A full return-to-office means I either spend half my salary on daycare or resign.',
    },
    {
      id: 'sh-3-2',
      name: 'Neurodivergent Employees',
      role: 'Staff with sensory sensitivities or ADHD',
      impact: 'negative',
      isOverlooked: true,
      voiceArchetype: 'default',
      description:
        'Struggle in open-plan office noise levels, experiencing sensory overload and reduced productivity compared to controlled home offices.',
      voiceQuote:
        'The open office is constant noise and distraction. At home, I can focus and get my tasks done in half the time without sensory exhaustion.',
    },
    {
      id: 'sh-3-3',
      name: 'Junior Engineers',
      role: 'Recent graduates and interns',
      impact: 'mixed',
      isOverlooked: false,
      voiceArchetype: 'worker',
      description:
        'Benefit from spontaneous mentorship and organic networking, but struggle with high rent near the downtown office.',
      voiceQuote:
        'I learn so much more sitting next to senior devs. But finding an affordable apartment within commuting distance is almost impossible.',
    },
    {
      id: 'sh-3-4',
      name: 'Executive Leadership',
      role: 'C-Suite and directors',
      impact: 'positive',
      isOverlooked: false,
      voiceArchetype: 'authority',
      description:
        'Believe physical collocation increases company culture, faster decision making, and justifies long-term office leases.',
      voiceQuote:
        'Collaboration happens in hallways, not scheduled video calls. We need our people together to spark the next wave of innovation.',
    },
  ],
};

export const MOCK_SIMULATIONS: SimulationRecord[] = [
  ATTENDANCE_SIMULATION,
  CASHLESS_SIMULATION,
  RTO_SIMULATION,
];
