import React from 'react';
import { StyleSheet, View } from 'react-native';
import { ThemedText } from './themed-text';
import { ThemedView } from './themed-view';
import { SimulationRecord } from '@/constants/mockData';
import { calculateEquityScore, getEquityLabel } from './EquityIndex';

export interface ReportCardProps {
  simulation: SimulationRecord | null;
  language?: 'en-IN' | 'hi-IN' | 'te-IN';
}

const REPORT_TRANSLATIONS = {
  'en-IN': {
    brandSubtitle: 'Decision Blind Spot Detector',
    policyAnalyzed: 'POLICY ANALYZED',
    equityIndex: 'EQUITY INDEX',
    blindSpotsDetected: (count: number) => `BLIND SPOTS DETECTED: ${count}`,
    noBlindSpots: 'No significant blind spots detected.',
    conflictsDetected: (count: number) => `CONFLICTS DETECTED: ${count}`,
    stakeholdersAnalyzed: (count: number) => `STAKEHOLDERS ANALYZED: ${count}`,
    analyzedOn: (date: string) => `Analyzed on ${date}`,
    generatedByEcho: 'Generated by Echo — Decision Blind Spot Detector',
  },
  'hi-IN': {
    brandSubtitle: 'निर्णय ब्लाइंड स्पॉट डिटेक्टर',
    policyAnalyzed: 'विश्लेषण की गई नीति',
    equityIndex: 'इक्विटी इंडेक्स',
    blindSpotsDetected: (count: number) => `पाए गए ब्लाइंड स्पॉट: ${count}`,
    noBlindSpots: 'कोई महत्वपूर्ण ब्लाइंड स्पॉट नहीं पाया गया।',
    conflictsDetected: (count: number) => `पाए गए संघर्ष: ${count}`,
    stakeholdersAnalyzed: (count: number) => `विश्लेषण किए गए हितधारक: ${count}`,
    analyzedOn: (date: string) => `विश्लेषण की तिथि: ${date}`,
    generatedByEcho: 'इको द्वारा जनरेट किया गया — निर्णय ब्लाइंड स्पॉट डिटेक्टर',
  },
  'te-IN': {
    brandSubtitle: 'నిర్ణయ బ్లైండ్ స్పాట్ డిటెక్టర్',
    policyAnalyzed: 'విశ్లేషించబడిన విధానం',
    equityIndex: 'ఈక్విటీ ఇండెక్స్',
    blindSpotsDetected: (count: number) => `కనుగొనబడిన బ్లైండ్ స్పాట్‌లు: ${count}`,
    noBlindSpots: 'ఎటువంటి ముఖ్యమైన బ్లైండ్ స్పాట్‌లు కనుగొనబడలేదు.',
    conflictsDetected: (count: number) => `కనుగొనబడిన వైరుధ్యాలు: ${count}`,
    stakeholdersAnalyzed: (count: number) => `విశ్లేషించబడిన స్టేక్‌హోల్డర్‌లు: ${count}`,
    analyzedOn: (date: string) => `విశ్లేషించబడిన తేదీ: ${date}`,
    generatedByEcho: 'ఎకో ద్వారా రూపొందించబడింది — నిర్ణయ బ్లైండ్ స్పాట్ డిటెక్టర్',
  },
};

export function ReportCard({ simulation, language }: ReportCardProps) {
  if (!simulation) return null;

  const score = calculateEquityScore(
    simulation.stakeholders || [],
    simulation.conflicts || [],
    simulation.blindSpots || []
  );

  const blindSpotsCount = simulation.blindSpots?.length || 0;
  const label = getEquityLabel(score, blindSpotsCount, language);

  const getColor = (val: number) => {
    if (val >= 80) return '#4CD964'; // Green
    if (val >= 50) return '#FFCC00'; // Amber
    return '#FF3B30'; // Red
  };

  const riskColor = getColor(score);

  const currentLang = language || 'en-IN';
  const t = REPORT_TRANSLATIONS[currentLang] || REPORT_TRANSLATIONS['en-IN'];
  const formattedDate = new Date().toLocaleDateString(currentLang, { month: 'short', day: 'numeric', year: 'numeric' });

  return (
    <View style={styles.hiddenWrapper}>
      {/* This ID is targeted by html2canvas */}
      <View nativeID="report-card-export" style={styles.cardContainer}>
        
        {/* Header */}
        <View style={styles.header}>
          <ThemedText style={styles.brandTitle}>
            <ThemedText style={styles.brandDot}>🔵</ThemedText> ECHO
          </ThemedText>
          <ThemedText style={styles.brandSubtitle}>{t.brandSubtitle}</ThemedText>
        </View>

        <View style={styles.divider} />

        {/* Policy Section */}
        <View style={styles.section}>
          <ThemedText style={styles.sectionLabel}>{t.policyAnalyzed}</ThemedText>
          <ThemedText style={styles.policyTitle}>"{simulation.decisionTitle}"</ThemedText>
        </View>

        <View style={styles.divider} />

        {/* Equity Index */}
        <View style={styles.section}>
          <ThemedText style={styles.sectionLabel}>{t.equityIndex}</ThemedText>
          <View style={styles.scoreRow}>
            <View style={styles.barBackground}>
              <View style={[styles.barFill, { width: `${score}%`, backgroundColor: riskColor }]} />
            </View>
            <ThemedText style={[styles.scoreValue, { color: riskColor }]}>{score} / 100</ThemedText>
          </View>
          <ThemedText style={[styles.riskLabel, { color: riskColor }]}>{label}</ThemedText>
        </View>

        <View style={styles.divider} />

        {/* Blind Spots */}
        <View style={styles.section}>
          <ThemedText style={styles.sectionLabel}>{t.blindSpotsDetected(blindSpotsCount)}</ThemedText>
          {simulation.blindSpots && simulation.blindSpots.length > 0 ? (
            <View style={styles.list}>
              {simulation.blindSpots.map((bs, idx) => (
                <ThemedText key={idx} style={styles.listItem}>🔴 {bs}</ThemedText>
              ))}
            </View>
          ) : (
            <ThemedText style={styles.listItem}>{t.noBlindSpots}</ThemedText>
          )}
        </View>

        <View style={styles.divider} />

        {/* Stats */}
        <View style={styles.section}>
          <ThemedText style={styles.sectionLabel}>{t.conflictsDetected(simulation.conflicts?.length || 0)}</ThemedText>
          <ThemedText style={styles.sectionLabel}>{t.stakeholdersAnalyzed(simulation.stakeholders?.length || 0)}</ThemedText>
        </View>

        <View style={styles.divider} />

        {/* Footer */}
        <View style={styles.footer}>
          <ThemedText style={styles.footerText}>
            {t.analyzedOn(formattedDate)}
          </ThemedText>
          <ThemedText style={styles.footerText}>echo-app.vercel.app</ThemedText>
          <ThemedText style={[styles.footerText, { marginTop: 16, opacity: 0.6 }]}>
            {t.generatedByEcho}
          </ThemedText>
        </View>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  hiddenWrapper: {
    // Hide from normal view, but keep mounted so it can be captured
    position: 'absolute',
    top: -9999,
    left: -9999,
    opacity: 0,
    pointerEvents: 'none',
  },
  cardContainer: {
    width: 600,
    backgroundColor: '#0A0A0F',
    padding: 40,
    borderWidth: 1,
    borderColor: '#2A2A3A',
    borderRadius: 16,
  },
  header: {
    marginBottom: 24,
  },
  brandTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: '#E8E8F0',
    letterSpacing: 1,
  },
  brandDot: {
    fontSize: 24,
    color: '#6E56FF', // Purple/blue accent approximation for emoji replacement if needed
  },
  brandSubtitle: {
    fontSize: 16,
    color: '#8B8B9E',
    marginTop: 4,
    fontWeight: '500',
  },
  divider: {
    height: 1,
    backgroundColor: '#2A2A3A',
    marginVertical: 24,
  },
  section: {
    gap: 8,
  },
  sectionLabel: {
    fontSize: 14,
    fontWeight: '800',
    color: '#8B8B9E',
    letterSpacing: 1.5,
  },
  policyTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#FFFFFF',
    lineHeight: 32,
  },
  scoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    marginTop: 8,
  },
  barBackground: {
    flex: 1,
    height: 16,
    backgroundColor: '#1A1A24',
    borderRadius: 8,
    overflow: 'hidden',
  },
  barFill: {
    height: '100%',
    borderRadius: 8,
  },
  scoreValue: {
    fontSize: 24,
    fontWeight: '900',
    width: 100,
  },
  riskLabel: {
    fontSize: 16,
    fontWeight: '700',
    marginTop: 8,
  },
  list: {
    marginTop: 8,
    gap: 12,
  },
  listItem: {
    fontSize: 18,
    color: '#E8E8F0',
    fontWeight: '500',
  },
  footer: {
    marginTop: 8,
  },
  footerText: {
    fontSize: 14,
    color: '#8B8B9E',
    lineHeight: 24,
  },
});
